apiVersion: v2
name: straitkubegateway
description: Cloud-native eBPF-powered CNI, Gateway API, Transit Gateway, and kube-proxy replacement for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
home: "https://github.com/straitKubegateway/straitKubegateway"
sources:
  - https://github.com/straitKubegateway/straitKubegateway
keywords:
  - networking
  - cni
  - ebpf
  - gateway-api
  - kubeproxy-replacement
  - bgp
  - transit-gateway
  - wireguard
maintainers:
  - name: straitKubegateway Team
    email: maintainers@strait.io

dependencies:
  - name: crd
    version: 1.0.0
    repository: "file://charts/crd"
  - name: custom_resource
    version: 1.0.0
    repository: "file://charts/custom_resource"
  - name: custom_controller
    version: 1.0.0
    repository: "file://charts/custom_controller"
