{{- if and .Values.sgController.autoscaling .Values.sgController.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
  minReplicas: {{ .Values.sgController.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.sgController.autoscaling.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sgController.autoscaling.targetCPUUtilizationPercentage | default 80 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sgController.autoscaling.targetMemoryUtilizationPercentage | default 80 }}
{{- end }}
