{{- if and .Values.secret .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-secret
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
