apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-straitd
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
