apiVersion: v1
kind: Service
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sgController.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "straitKubegateway-helm-repo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
---
{{- if .Values.straitd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-straitd
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.straitd.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "straitKubegateway-helm-repo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-ui
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "straitKubegateway-helm-repo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
