{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-straitd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "straitKubegateway-helm-repo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-agent
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "straitKubegateway-helm-repo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "15s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
