{{- if .Values.gatewayAPI.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: {{ include "straitKubegateway-helm-repo.fullname" . }}-udp-route
  labels:
    {{- include "straitKubegateway-helm-repo.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "straitKubegateway-helm-repo.fullname" . }}-gateway
      sectionName: udp
  rules:
    - backendRefs:
        - name: {{ include "straitKubegateway-helm-repo.fullname" . }}-controller
          port: 9001
{{- end }}
