apiVersion: v1
kind: Service
metadata:
  name: {{ include "straitKubegateway.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitKubegateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.controller.grpc.port }}
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: {{ .Values.controller.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "straitKubegateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
