apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "straitKubegateway.agentServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitKubegateway.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "straitKubegateway.controllerServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "straitKubegateway.labels" . | nindent 4 }}
