apiVersion: strait.io/v1alpha1
kind: Segment
metadata:
  name: backbone-segment
  labels:
    app.kubernetes.io/name: straitkubegateway
spec:
  id: 0
  isolated: false
  backboneConnected: true
---
apiVersion: strait.io/v1alpha1
kind: IPAMPool
metadata:
  name: default-pool
  labels:
    app.kubernetes.io/name: straitkubegateway
spec:
  cidrs:
    - "10.244.0.0/16"
  perNodeMaskSize: 24
  addressFamily: "IPv4"
